authentic/urls.py
from django.urls import path 
from .views import (
    login_view, 
    logout_view, 
    signup_view, 
    update_password, 
)

app_name = 'authentic'

urlpatterns = [
    path('login', login_view, name='login'), 
    path('logout', logout_view, name='logout'), 
    path('signup', signup_view, name='signup'), 
    path('update_password', update_password, name='update_password')
]

blogger/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentic.urls')), 
    path('', include('core.urls')), 
]

core/urls.py
from django.urls import path 
from .views import (
    blogListView,
    blogCreateView, 
    blogDeleteView, 
    blogDetailsView, 
    blogUpdateView, 
    commentCreateView, 
    blogCategoriesView, 
)

app_name = 'core' 
urlpatterns = [
    path('', blogListView, name='home'),
    path('create', blogCreateView, name='create'), 
    path('<int:id>/delete', blogDeleteView, name='delete'), 
    path('<int:id>/', blogDetailsView, name='detail'), 
    path('<int:id>/update', blogUpdateView, name='update'),
    path('<int:id>/comment-create', commentCreateView, name='create-comment'), 
    path('categories', blogCategoriesView, name='categories'),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User

# # Create your models here.
# Post => title, content, author, date_published 
# Category => name 
# Tag => name 
# Comment => username, content

CATEGORY_OPTIONS = [
        ('tech', 'Technology'), 
        ('business', 'Business'), 
        ('health and wellness', 'Health And Wellness'), 
        ('travel', 'Travel'), 
        ('food and clothing', 'Food And Clothing'), 
        ('lifestyle', 'Lifestyle'), 
        ('finance and investing', 'Finance And Investing'), 
        ('education', 'Education'), 
        ('faith', 'Faith'), 
        ('entertainment', 'Entertainment'),
        ('environment and sustainability', 'Environment And Sustainability'), 
        ('arts and culture', 'Arts And Culture')
    ]

class Tag(models.Model):
    name = models.CharField(max_length=100, unique=True) 

    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    author = models.CharField(max_length=100, null=False, default='') 
    category = models.CharField(choices=CATEGORY_OPTIONS, max_length=100, default='')
    date_published = models.DateField(auto_now=True) 
    tags = models.ManyToManyField(Tag, blank=True)

    def __str__(self):
        return self.title 

class Comment(models.Model):
    username = models.CharField(max_length=100) 
    content = models.TextField(null=False, default='')
    post = models.ForeignKey(Post, on_delete=models.CASCADE) 

core/forms.py
from django import forms
from .models import (
    Post, Tag, Comment
)

class PostForm(forms.ModelForm):
    class Meta: 
        model = Post 
        fields = [
            'title', 'content', 'category', #'tags'
        ]

class TagForm(forms.ModelForm):
    class Meta: 
        model = Tag 
        fields = ['name']

class CommentForm(forms.ModelForm): 
    class Meta: 
        model = Comment 
        fields = [
            'username', 'content'
        ]

core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# from django.contrib.auth.models import User
from .models import Post, Tag, Comment, CATEGORY_OPTIONS
# from .forms import PostForm, TagForm, CommentForm

# Create your views here.
def blogCategoriesView(request):
    categories = [option[1] for option in CATEGORY_OPTIONS]
    post_categories = []
    for category in categories: 
        post_categories.append(
            list(Post.objects.filter(category=category))
        )
    print(post_categories)
    cat_and_posts = zip(categories, post_categories)
    context = {
        'category_options': categories, 
        'cats_and_posts': cat_and_posts,
        # 'post_categories': post_categories
    }
    return render(request, 'core/blog_categories.html', context)

def commentCreateView(request, id): # id of post being viewed
    if request.method == 'POST': 
        post = Post.objects.get(id=id)
        if request.POST['username'] or request.POST['content']:
            new_comment = Comment.objects.create(
                username=request.POST['username'], 
                content=request.POST['content'], 
                post=post
            )
            new_comment.save()
        else: 
            messages.success(request, ("Empty comments or usernames are not accepted"))
        return redirect(reverse('core:detail', kwargs={'id': id}))
    else:
        return redirect(reverse('core:detail', kwargs={'id': id}))

@login_required(login_url='authentic:login')
def blogDeleteView(request, id):
    post = Post.objects.get(id=id) 
    if request.method == 'POST':  
        post.delete()
        print('Post has been deleted')
        return redirect(reverse('core:home')) 
    print('Post not deleted')
    return render(request, 'core/blog_delete.html', {'post': post}) 

@login_required(login_url='authentic:login')
def blogUpdateView(request, id):
    post = Post.objects.get(id=id) 
    if request.method == 'POST' and post.author == request.user.username: 
        response = request.POST
        # print(response)
        title = response['title'] 
        content = response['content'] 
        tags_checked = [name[4:] for name in list(response.keys()) if name.startswith('tag_')]
        tags_typed = response['new_tags'].split(',')
        tags_typed = [tag_name.strip() for tag_name in tags_typed]
        all_tags = tags_checked + tags_typed
        # print('All tags', all_tags)
        post.title = title 
        post.content = content
        for tag_name in all_tags:
            if tag_name.strip():
                tag, created = Tag.objects.get_or_create(name=tag_name.lower()) 
                post.tags.add(tag) 
        post.save()
        return redirect(reverse('core:detail', kwargs={'id': id}))

    context = {
        'post': post, 
        'category_options': [option[1] for option in CATEGORY_OPTIONS], 
        'all_tags': Tag.objects.all(), 
        'cat_name': post.category.title()
    }
    return render(request, 'core/blog_update.html', context) 

@login_required(login_url='authentic:login')
def blogCreateView(request):
    if request.method == 'POST': 
        response = request.POST
        title = response['title'] 
        content = response['content']
        category = response['category'] 
        new_post = Post.objects.create(
            title=title, 
            content=content, 
            category=category, 
            author=request.user.username
        )
        new_post.save()
        tag_names = [name[4:] for name in list(response.keys()) if name.startswith('tag_')]
        new_tags_lists = response['new_tags'].split(',')
        new_tags = [tag_name.strip() for tag_name in new_tags_lists]
        new_tags.extend(tag_names)
        # Create new tags 
        for tag_name in new_tags:
            # print('tag_name', tag_name)
            if tag_name.strip():
                tag, created = Tag.objects.get_or_create(name=tag_name.lower()) 
                new_post.tags.add(tag) 
        new_post.save()
        return redirect(reverse('core:detail', kwargs={'id':new_post.id}))

    context = {
        'category_options': [option[1] for option in CATEGORY_OPTIONS], 
        'all_tags': Tag.objects.all()
    }
    return render(request, 'core/blog_create.html', context)

def blogDetailsView(request, id):
    post = get_object_or_404(Post, id=id)
    edit_authorisation = False
    if post.author == request.user.username: 
        edit_authorisation = True
    return render(request, 'core/blog_detail.html', {
                'post': post, 
                'edit_authorisation': edit_authorisation
            })

def blogListView(request):
    blog_feed = Post.objects.all()
    context = {
        'blog_feed': blog_feed
    }
    return render(request, 'core/blog_list.html', context)

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% include 'core/navigation.html' %}
    {% if messages %} 
        {% for message in messages %} 
            <div class="alert alert-warning alert-dismissible fade show bg-info text-white" role="alert">
                {{ message }}  
            </div>  
        {% endfor %}
    {% endif %} 

    {% block content %}{% endblock %}

    {% include 'core/footer.html' %} 
</body>
</html>

core/templates/core/blog_categories.html
{% extends 'core/base.html' %} 

{% block title %}Categories{% endblock %} 

{% block content %} 

<div class="container-fluid">
    <!-- <div class="collapse"></div> -->
        <ul>
            {% for cat, posts in cats_and_posts %} 
            <div class="container border border-dark rounded px-1 py-1 mb-2">
                <div class=" border border-warning rounded p-1">
                    <li class="nav-link">
                        {{ cat }}
                        <ul>
                            {% for post in posts %}
                            <li><a href="{% url 'core:detail' post.id %}" class="text-dark">{{ post.title }}</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                    </div>
            </div>
            {% endfor %}
        </ul>
</div>

{% endblock %} 

core/templates/core/blog_create.html
{% extends 'core/base.html' %} 

{% block title %}Create post{% endblock %} 

{% block content %} 

<div class="">
    <div class="container-fluid bg-dark text-white row py-lg-5 mb-4">
        <div class="my-5 text-center bg-dark display-3">
            Create Post
        </div>
    </div>
    <div class="container">
        <!-- this enctype means allow images -->
        <form class="form form-control" action="" method="post" enctype="multipart/form-data">{% csrf_token %}

            <!-- Post -->
            <label for="title" class="label form-control text-muted bg-dark my-3">
                <input type="text" name="title" class="form-control" placeholder="Title">
            </label>
            <label for="description" class="label form-control bg-warning my-3">
                <textarea name="content" id="" cols="30" rows="10" placeholder="Write here..." class="form-control"></textarea>
            </label>
            <label for="title" class="label form-control text-muted bg-dark my-3"><span class="text-white">Choose category</span>
                <select class="form-control" name="category" id="">
                    {% for option in category_options %} 
                    <option value="{{ option }}">{{ option|title }}</option>
                    {% endfor %}
                </select>
            </label>
            
            <!-- Tags -->
            <div class="tags card card-body my-3 bg-dark">
                <div class="card-header text-white">Choose or create tags</div>
                <div class="card-text mt-3">
                    <div class="row container">
                        {% for tag in all_tags %}
                        <div class="col-2 mx-1 my-1 bg-secondary text-white px-1 py-1border rounded rounded-4">
                            <label for="tag_{{ tag.name }}" class="bg-secondary label form-control check-input border-secondary text-white">
                                <input type="checkbox" name="tag_{{ tag.name }}" id="">
                                <span>{{ tag.name }}</span>
                            </label>
                        </div>                        
                        {% endfor %}
                    </div>
                </div>
                <div class="card-footer">
                    <input type="text" name="new_tags" id="" class="form-control" placeholder="Enter tags, seperate with commas...">
                </div>
            </div>

            <!-- Submit -->
            <div class="mt-3 btn btn-outline-warning form-control">
                <input class="form-control border border-secondary" type="submit" value="Save">
            </div>
        </form>
    </div>

</div>


{% endblock %}

core/templates/core/blog_delete.html
{% extends 'core/base.html' %} 

{% block title %}Delete post{% endblock %}

{% block content %} 

<div class="container-fluid bg-dark text-white text-center">
    <div class="my-0 py-5 display-6">
        Delete post
    </div>
    <div class="py-3 h3">
        {{ post.title }}
    </div>
</div>

<div class="container">
    <div class="text-center">
        <hr>
        <p class="h4 text-muted">This action cannot be undone</p>
        <hr>
    </div>
    <form action="" method="post">{% csrf_token %}
        <div class="row">
            <div class="col mx-3">
                <a href="{% url 'core:detail' post.id %}" class="form-control btn btn-secondary text-white">Cancel</a>
            </div>
            <button type="submit" class="col mx-3 form-control btn btn-danger text-white">Confirm</button>
        </div>
    </form>
</div>

{% endblock %}

core/templates/core/blog_detail.html
{% extends 'core/base.html' %} 

{% block title %}{{ post.title }}{% endblock %}

{% block styler %} 
<style>
hr.text-info {
    height: 3px;
    color: black;
    width: 30px;
}
</style>
{% endblock %}

{% block content %} 

<div>
    <hr class="text-info my-0">
    <div class="container-fluid bg-dark text-white text-center">
        <div class="my-0 py-5 display-6">
            {{ post.title }}
        </div>
    </div>
    <div class="container mt-3">
        <div class="card card-body">

            <div class="card-header">
                <div class="row">
                    <div class="col">{{ post.author }}</div>
                    <div class="col-2 text-muted me-0">{{ post.date_published }}</div>
                </div>
            </div>

            <div class="card-text">
                {{ post.content }}
                <hr>
                <div class="row bg-dark text-warning border border-warning">
                    <p>{% for tag in post.tags.all %} 
                        <span class=" mx-3">#{{ tag }}</span>
                    {% endfor %}
                    </p>
                </div>
            </div>

            <!-- Comments -->
            <div class="card-footer mt-4">
                {% if post.comment_set.all %}
                    <div class="h5">Comments</div>
                {% endif %}
                {% for comment in post.comment_set.all reversed %}
                <hr>
                    <div class="row">
                        <div class="col-5 text-center text-warning container">
                            <div class=" bg-secondary rounded p-2">{{ comment.username }}</div>
                        </div>                        
                        <div class="col-7"></div>
                    </div>
                    <p>{{ comment.content }}</p>
                {% endfor %}
            </div>

            {% if user.is_authenticated and edit_authorisation %} 
            <div class="row">
                <div class="col mx-3">
                    <a href="{% url 'core:update' post.id %}" class="form-control btn btn-dark text-white">Edit</a>
                </div>
                <div class="col mx-3">
                    <a href="{% url 'core:delete' post.id %}" class="form-control btn btn-danger text-white">Delete</a>
                </div>
            </div>
            {% endif %}
        </div>

        <div class="mt-5 card border border-secondary">
            <div class="card-header">Comment on this post</div>
            <div class="card-text px-2">
                <form action="../{{ post.id }}/comment-create" class="form" method="post">{% csrf_token %}
                    <label for="username" class="form-control">
                        <input type="text" name="username" id="" class="form-control"
                            placeholder="Username">
                    </label>
                    <label for="content" class="form-control">
                        <input type="text" name="content" id="" class="form-control"
                            placeholder="Enter comment...">
                    </label>
                    <div class="form-control">
                        <input type="submit" value="Done" class="btn btn-dark text-white">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

core/templates/core/blog_list.html
{% extends 'core/base.html' %} 

{% block title %}Home{% endblock %} 

{% block content %} 
<div class="container-fluid bg-dark mb-5 text-warning p-5">
    <div class="jumbotron bg-dark py-5 text-center">
        <h1 class="display-2">Welcome to My Blog!!</h1>
    </div>
    <div class="row">
        <div class="col-10">
            {% if user.is_authenticated %}
            <a href="{% url 'core:create' %}" class="btn btn-white bg-light">Create Post</a>
            {% endif %}
        </div>
        <div class="col-2 text-white">{{ user.username }}</div>
    </div>
</div>

<div class="container my-2">
    {% for post in blog_feed reversed %} 
    <div class="row mt-4 shadow">
        <div class="card card-block border border-dark">
            <div class="card-header">
                <a href="{% url 'core:detail' post.id %}" class="btn btn-lg form-control h3">
                    <span class="h3">{{ post.title }}</span>
                </a>
            </div>
            <!-- <div class="card-body">
                {{ post.content }}
            </div> -->
            <div class="card-footer">
                <div class="row">
                    <div class="col">Category: <span class="h6">{{ post.category|title }}</span></div>
                    <div class="col">Tags: 
                        {% for tag in post.tags.all %}
                            <span class="h6">{{ tag }}</span>{% if not forloop.last %},{% endif %}
                        {% endfor %}
                    </div>
                    {% if post.author %}<div class="col text-primary">{{ post.author }}</div>{% endif %}
                    <div class="col text-primary">{{ post.date_published }}</div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %} 

core/templates/core/blog_update.html
{% extends 'core/base.html' %} 

{% block title %}Create post{% endblock %} 

{% block content %} 

<div class="">
    <div class="container-fluid bg-dark text-white row py-lg-5 mb-4">
        <div class="my-5 text-center bg-dark display-3">
            Update Post
        </div>
    </div>
    <div class="container">
        <!-- this enctype means allow images -->
        <form class="form form-control" action="" method="post">{% csrf_token %}

            <!-- Post -->
            <label for="title" class="label form-control text-muted bg-dark my-3">
                <input type="text" name="title" class="form-control" 
                    placeholder="Title" value="{{ post.title }}">
            </label>
            <label for="description" class="label form-control bg-warning my-3">
                <textarea name="content" id="" cols="30" rows="10" placeholder="Write here..." class="form-control">{{ post.content }}</textarea>
            </label>
            <label for="title" class="label form-control text-muted bg-dark my-3"><span class="text-white">Choose category</span>
                <select class="form-control" name="category" id="">
                    {% for option in category_options %} 
                    <option 
                    value="{{ option }}"
                    {% if option == cat_name %} selected="selected" {% endif %}>
                    {{ option|title }}
                    </option>
                    {% endfor %}
                </select>
            </label>
            
            <!-- Tags -->
            <div class="tags card card-body my-3 bg-dark">
                <div class="card-header text-white">Choose or create tags</div>
                <div class="card-text mt-3">
                    <div class="row container">
                        {% for tag in all_tags %}
                        
                        <div class="col-2 mx-1 my-1 bg-secondary text-white px-1 py-1border rounded rounded-4">
                            <label for="tag_{{ tag.name }}" class="bg-secondary label form-control check-input border-secondary text-white">
                                <input 
                                    type="checkbox" 
                                    name="tag_{{ tag.name }}" 
                                    id=""
                                    {% if tag in post.tags.all %}checked{% endif %}>
                                <span>{{ tag.name }}</span>
                            </label>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="card-footer">
                    <input type="text" name="new_tags" id="" class="form-control" placeholder="Enter tags, seperate with commas...">
                </div>
            </div>

            <!-- Submit -->
            <div class="row">
                <div class="col">
                    <div class="mt-3 ">
                        <a href="{% url 'core:detail' post.id %}" class="btn btn-outline-warning form-control">Cancel</a>
                    </div>
                </div>
                <div class="col">
                    <div class="mt-3 btn btn-outline-warning form-control">
                        <input class="form-control border border-secondary" type="submit" value="Save">
                    </div>
                </div>
            </div>
        </form>
    </div>

</div>


{% endblock %}

core/templates/core/navigation.html
<div class="blog-nav">
    <div class="blog-nav-list ">
        <div class="row px-auto bg-dark py-4">
            <div class="col "><a href="{% url 'core:home' %}" class="btn btn-bd-primary text-white">Home</a></div>
            <div class="col px-auto mx-auto"><a href="{% url 'core:categories' %}" class="btn btn-bd-primary text-white">Categories</a></div> 
            <!-- <div class="col"><a href="" class="btn btn-bd-primary text-white">Favourites</a></div>  -->
            <!-- <div class="col"><a href="" class="btn btn-bd-primary text-white">Cart</a></div> -->
            {% if not user.is_authenticated %}
                <div class="col"><a href="{% url 'authentic:signup' %}" class="btn btn-bd-primary text-white">Sign Up</a></div>
                <div class="col"><a href="{% url 'authentic:login' %}" class="btn btn-bd-primary text-white">Log In</a></div>
            {% else %} 
                <div class="col"><a href="{% url 'authentic:update_password' %}" class="btn btn-bd-primary text-white">Change Password</a></div>
                <div class="col"><a href="{% url 'authentic:logout' %}" class="btn btn-bd-primary text-white">Log Out</a></div>
            {% endif %}
        </div>
        <hr class="shadow">
    </div>
</div>